
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * searchcustomer.java
 *
 * Created on Feb 3, 2019, 12:09:39 PM
 */

/**
 *
 * @author PC
 */
public class searchcustomer extends javax.swing.JFrame {

    /** Creates new form searchcustomer */
    public searchcustomer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setForeground(new java.awt.Color(0, 204, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel3.setForeground(new java.awt.Color(0, 204, 102));
        jLabel3.setText("SEARCH CUSTOMER DETAILS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel3)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t1.setFont(new java.awt.Font("Tahoma", 0, 18));

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ADMISSION NUMBER", "NAME", "PH.NUMBER", "DATE OF JOINING", "BLOOOD GROUP", "HEIGHT", "WEIGHT", "BMI", "HEALTH ISSUE", "TYPE", "PACKAGE", "ADDRESS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt1);

        r1.setFont(new java.awt.Font("Tahoma", 0, 18));
        r1.setText("MALE");

        r2.setFont(new java.awt.Font("Tahoma", 0, 18));
        r2.setText("FEMALE");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("SELECT GENDER");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cb1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADMISSION NUMBER", "CUSTOMER NAME", "PHONE NUMBER", "DATE OF JOINING", "ADDRESS" }));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(201, 201, 201)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(r1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r2))
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(399, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(478, 478, 478)
                .addComponent(jButton1)
                .addContainerGap(672, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1227, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(jButton3)
                .addContainerGap(675, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(r1)
                    .addComponent(r2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel m=(DefaultTableModel)jt1.getModel();
        String c=(String)cb1.getSelectedItem();
        if(c.equals("ADMISSION NUMBER")) {
            if(r1.isSelected()) {
                int a=Integer.parseInt(t1.getText());
                try{
                    Class.forName("java.sql.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/everyouth","root","gokul");
                    Statement s=con.createStatement();
                    String q="Select * from mmem where adno="+a+";";
                    ResultSet rs=s.executeQuery(q);

                    while(rs.next()) {
                        int adno=rs.getInt("adno");
                        String name=rs.getString("name");
                        String ph=rs.getString("phnum");

                        String doj=rs.getString("doj");
                        String bg=rs.getString("bloodgroup");
                        String h=rs.getString("height");
                        String w=rs.getString("weight");
                        String bmi=rs.getString("BMI");
                        String hi=rs.getString("healthisssue");
                        String t=rs.getString("type");
                        String p=rs.getString("package");
                        String ad=rs.getString("address");
                        Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                        m.addRow(ta);
                    }


                }catch(Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }

            else if(r2.isSelected()) {
                int a=Integer.parseInt(t1.getText());
                try{
                    Class.forName("java.sql.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/everyouth","root","gokul");
                    Statement s=con.createStatement();
                    String q="Select * from fmem where adno="+a+";";
                    ResultSet rs=s.executeQuery(q);

                    while(rs.next()) {
                        int adno=rs.getInt("adno");
                        String name=rs.getString("name");
                        String ph=rs.getString("phnum");
                
                        String doj=rs.getString("doj");
                        String bg=rs.getString("bloodgroup");
                        String h=rs.getString("height");
                        String w=rs.getString("weight");
                        String bmi=rs.getString("BMI");
                        String hi=rs.getString("healthisssue");
                        String t=rs.getString("type");
                        String p=rs.getString("package");
                        String ad=rs.getString("address");
                        Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                        m.addRow(ta);
                    }

                }catch(Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }
        } else{
            if(r1.isSelected()) {
                String a=t1.getText();
                String q;
                try{
                    Class.forName("java.sql.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/everyouth","root","gokul");
                    Statement s=con.createStatement();
                    if(c.equals("CUSTOMER NAME")) {
                        q="Select * from mmem where trim(name) like '%"+a+"%';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                       
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                    if(c.equals("PHONE NUMBER")) {
                        q="Select * from mmem where trim(phnum)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                           
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                  
                    if(c.equals("DATE OF JOINING")) {
                        q="Select * from mmem where trim(doj)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                            
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                    if(c.equals("ADDRESS")) {
                        q="Select * from mmem where trim(address)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                            
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }




                }catch(Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }

            if(r2.isSelected()) {
                String a=t1.getText();
                String q;
                try{
                    Class.forName("java.sql.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/everyouth","root","gokul");
                    Statement s=con.createStatement();
                    if(c.equals("CUSTOMER NAME")) {
                        q="Select * from fmem where trim(name) like '%"+a+"%';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                           
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                    if(c.equals("PHONE NUMBER")) {
                        q="Select * from fmem where trim(phnum)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                           
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                    if(c.equals("EMAIL ID")) {
                        q="Select * from fmem where trim(emailid)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                            
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                    if(c.equals("DATE OF JOINING")) {
                        q="Select * from fmem where trim(doj)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                          
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }
                    if(c.equals("ADDRESS")) {
                        q="Select * from fmem where trim(address)='"+a+"';";
                        ResultSet rs=s.executeQuery(q);

                        while(rs.next()) {
                            int adno=rs.getInt("adno");
                            String name=rs.getString("name");
                            String ph=rs.getString("phnum");
                           
                            String doj=rs.getString("doj");
                            String bg=rs.getString("bloodgroup");
                            String h=rs.getString("height");
                            String w=rs.getString("weight");
                            String bmi=rs.getString("BMI");
                            String hi=rs.getString("healthisssue");
                            String t=rs.getString("type");
                            String p=rs.getString("package");
                            String ad=rs.getString("address");
                            Object[] ta={adno,name,ph,doj,bg,h,w,bmi,hi,t,p,ad};
                            m.addRow(ta);
                        }
                    }




                }catch(Exception e) {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
            }
















        }// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new homepage().setVisible(true);

        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel m=(DefaultTableModel)jt1.getModel();
        m.setRowCount(0);









        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
